name: CI RentABikeWebApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repo
        uses: actions/checkout@v3
        with:
          path: RentABikeWebApp

      - name: Checkout tests repo
        uses: actions/checkout@v3
        with:
          repository: tcudor/TestsRentABikeWebApp
          path: TestsRentABikeWebApp

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build application
        working-directory: RentABikeWebApp
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Restore & Build tests
        working-directory: TestsRentABikeWebApp
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Run unit tests
        working-directory: TestsRentABikeWebApp
        run: dotnet test --configuration Release --verbosity normal

      - name: Publish WebApp
        working-directory: RentABikeWebApp
        run: |
          dotnet publish RentABikeWebApp.csproj \
            --configuration Release \
            --output ../publish
            
      - name: Upload publish artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: RentABikeWebApp-publish
          path: publish


