name: CI RentABikeWebApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application repo
        uses: actions/checkout@v3
        
      - name: Checkout tests repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/TestsRentABikeWebApp
          path: tests 
          
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore ./RentABikeWebApp/RentABikeWebApp.csproj
          dotnet restore ./tests/TestsRentABikeWebApp/TestsRentABikeWebApp.csproj

      - name: Build solution
        run: dotnet build RentABikeWebApp/RentABikeWebApp.sln --no-restore --configuration Release

      - name: Build test project
        run: dotnet build ./tests/TestsRentABikeWebApp/TestsRentABikeWebApp.csproj --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test ./tests/TestsRentABikeWebApp/TestsRentABikeWebApp.csproj --no-build --configuration Release --verbosity normal

      - name: Publish WebApp
        run: dotnet publish ./RentABikeWebApp/RentABikeWebApp.csproj \
              --configuration Release \
              --output ./publish
              
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-app-deploy
          path: RentABikeWebApp/RentABikeWebApp/deploy
