name: CI RentABikeWebApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout tests repo
        uses: actions/checkout@v3
        with:
          repository: tcudor/TestsRentABikeWebApp
          path: TestsRentABikeWebApp

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & build application
        run: |
          dotnet restore RentABikeWebApp.csproj
          dotnet build   RentABikeWebApp.csproj --no-restore --configuration Release

      - name: Restore & build tests
        run: |
          dotnet restore TestsRentABikeWebApp/TestsRentABikeWebApp.csproj
          dotnet build   TestsRentABikeWebApp/TestsRentABikeWebApp.csproj --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test TestsRentABikeWebApp/TestsRentABikeWebApp.csproj --no-build --verbosity normal

      - name: Publish WebApp
        run: dotnet publish RentABikeWebApp.csproj --configuration Release --output ./publish
